apiVersion: v2
appVersion: 1.0.0
description: Comabase helm package
name: comabase
version: 1.0.1
kubeVersion: ">=1.16.0-0"
keywords:
- comabase
home: https://github.com/imtoanle/charts/tree/master/charts/stable/comabase
icon: https://pics.freeicons.io/uploads/icons/png/21398484261551941708-512.png
sources:
- https://github.com/imtoanle/comabase
maintainers:
- name: imtoanle
  email: toanledev@gmail.com
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.5.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Trigger
