apiVersion: v2
appVersion: v4.8.14
description: NexoPOS helm package
name: nexopos
version: 0.1.0
kubeVersion: ">=1.16.0-0"
keywords:
- nexopos
home: https://github.com/imtoanle/charts/tree/master/charts/stable/nexopos
icon: https://pics.freeicons.io/uploads/icons/png/21398484261551941708-512.png
sources:
- https://github.com/Blair2004/NexoPOS
maintainers:
- name: imtoanle
  email: toanledev@gmail.com
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.5.2
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial version
