#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ktoanlba/nexopos
  # -- image tag
  tag: v4.8.14
  # -- image pull policy
  pullPolicy: IfNotPresent

# @default -- See below
env:
  # APP_NAME="NexoPOS 4.x"
  # APP_ENV=local
  # APP_KEY=
  # APP_DEBUG=true
  # APP_URL=http://127.0.0.1

  # LOG_CHANNEL=stack

  # DB_CONNECTION=mysql
  # DB_HOST=127.0.0.1
  # DB_PORT=3306
  # DB_DATABASE=laravel
  # DB_USERNAME=root
  # DB_PASSWORD=

  # BROADCAST_DRIVER=log
  # CACHE_DRIVER=file
  # QUEUE_CONNECTION=sync
  # SESSION_DRIVER=file
  # SESSION_LIFETIME=120
  # SESSION_DOMAIN=127.0.0.1
  # SESSION_COOKIE=nexopos_session

  # REDIS_HOST=127.0.0.1
  # REDIS_PASSWORD=null
  # REDIS_PORT=6379

  # MAIL_MAILER=smtp
  # MAIL_HOST=smtp.mailtrap.io
  # MAIL_PORT=2525
  # MAIL_USERNAME=null
  # MAIL_PASSWORD=null
  # MAIL_ENCRYPTION=null
  # MAIL_FROM_ADDRESS=null
  # MAIL_FROM_NAME="${APP_NAME}"

  # AWS_ACCESS_KEY_ID=
  # AWS_SECRET_ACCESS_KEY=
  # AWS_DEFAULT_REGION=us-east-1
  # AWS_BUCKET=

  # PUSHER_APP_ID=
  # PUSHER_APP_KEY=
  # PUSHER_APP_SECRET=
  # PUSHER_APP_CLUSTER=mt1

  # MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
  # MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
  # SANCTUM_STATEFUL_DOMAINS=http://127.0.0.1:8000/,http://localhost/,http://127.0.0.1/
  # NS_ENV=production

  # TELESCOPE_ENABLED=false


# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false
