#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ktoanlba/casper-node-exporter
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [casper-node-exporter documentation](https://casper-node-exporter.org/docs).
# @default -- See below
env:
  VALIDATOR_PUBLIC_KEY:
  OUR_NODE:

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    type: ClusterIP
    ports:
      http:
        port: 8111

metrics:
  # -- Enable and configure prometheus-qbittorrent-exporter sidecar and Prometheus podMonitor.
  # @default -- See values.yaml
  enabled: false
  serviceMonitor:
    interval: 15s
    scrapeTimeout: 5s
    labels: {}
