apiVersion: v2
description: Mattermost Team Edition server.
type: application
name: mattermost-team-edition
version: 6.6.19
appVersion: 7.7.1
keywords:
- mattermost
- communication
- team collaboration
home: https://mattermost.com
icon: http://www.mattermost.org/wp-content/uploads/2016/04/icon.png
sources:
- https://github.com/mattermost/mattermost-server
- https://github.com/mattermost/mattermost-helm
maintainers:
- name: imtoanle
  email: toanledev@gmail.com
dependencies:
- name: mysql
  version: 1.6.4
  repository: https://charts.helm.sh/stable
  condition: mysql.enabled
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Init
    - kind: changed
      description: Update
